name: busy_bee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^3.4.2
  go_router: ^17.5.0
  dynamic_backend_bridge:
    path: ../dynamic_backend_bridge
  firebase_core: ^4.13.0
  shared_preferences: ^2.5.5
  table_calendar: ^3.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#F8F9FA"
  color_dark: "#121212"
  image: assets/images/app_icon.png
  image_dark: assets/images/app_icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
